"""Coverage backlog for block provenance migration."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .freshness_index import build_inventory


def _page_kind(path: str) -> str:
    parts = Path(path).parts
    if len(parts) >= 2 and parts[0] == "wiki":
        return parts[1]
    return "wiki"


def _coverage_status(page: dict[str, Any]) -> str:
    if page.get("validation_issues"):
        return "invalid-provenance"
    if page.get("migration_status") == "legacy-inferred-minimal":
        return "minimal-stamp"
    blocks = page.get("blocks", [])
    if not blocks:
        return "legacy-no-block-ids"
    if all(block.get("has_provenance") for block in blocks):
        return "covered"
    if any(block.get("has_provenance") for block in blocks):
        return "partial-provenance"
    return "block-ids-without-provenance"


def _priority(status: str, kind: str) -> int:
    if status == "invalid-provenance":
        return 100
    if status == "partial-provenance":
        return 80
    if status == "block-ids-without-provenance":
        return 70
    if status == "minimal-stamp":
        return 45
    if kind in {"decisions", "problems", "systems", "projects"}:
        return 50
    if kind in {"concepts", "competition"}:
        return 40
    if kind == "people":
        return 30
    return 20


def build_coverage_backlog(root: Path) -> dict[str, Any]:
    """Return a complete wiki-page block-provenance coverage backlog."""
    root = root.resolve()
    inventory = build_inventory(root)
    pages: list[dict[str, Any]] = []
    by_status: dict[str, int] = {}
    by_kind: dict[str, int] = {}

    for page in inventory["wiki_pages"]:
        status = _coverage_status(page)
        kind = _page_kind(page["path"])
        by_status[status] = by_status.get(status, 0) + 1
        by_kind[kind] = by_kind.get(kind, 0) + 1
        if status != "covered":
            pages.append({
                "path": page["path"],
                "title": page["title"],
                "kind": kind,
                "coverage_status": status,
                "block_count": len(page.get("blocks", [])),
                "priority": _priority(status, kind),
                "validation_issues": page.get("validation_issues", []),
            })

    pages.sort(key=lambda item: (-item["priority"], item["kind"], item["path"]))
    return {
        "summary": {
            "wiki_pages": inventory["summary"]["wiki_pages"],
            "covered_pages": by_status.get("covered", 0),
            "backlog_pages": len(pages),
            "by_status": by_status,
            "by_kind": by_kind,
        },
        "pages": pages,
    }


def write_backlog(root: Path, result: dict[str, Any]) -> Path:
    """Write a markdown coverage backlog under `.wiki-scratch/`."""
    outdir = root / ".wiki-scratch"
    outdir.mkdir(exist_ok=True)
    path = outdir / "provenance-coverage-backlog.md"
    summary = result["summary"]
    lines = [
        "# Provenance coverage backlog",
        "",
        "Generated by `wiki-provenance-coverage.py`. This is a coverage backlog, not a freshness drift queue.",
        "",
        f"- Wiki pages: {summary['wiki_pages']}",
        f"- Covered pages: {summary['covered_pages']}",
        f"- Backlog pages: {summary['backlog_pages']}",
        "",
        "## Status Counts",
        "",
    ]
    for status, count in sorted(summary["by_status"].items()):
        lines.append(f"- {status}: {count}")
    lines.extend(["", "## Backlog", ""])
    for page in result["pages"]:
        page_link = page["path"][:-3]
        lines.append(
            f"- [ ] **[[{page_link}]]** "
            f"`{page['coverage_status']}` priority {page['priority']}"
        )
        lines.append(
            f"      <sub>kind: {page['kind']}; "
            f"blocks: {page['block_count']}</sub>"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
